---
- hosts: localhost
  tasks:
  - name: Install UFW
    apt:
      package: ufw

  - name: Disable UFW logging
    lineinfile:
      dest: /etc/ufw/ufw.conf
      regexp: "^LOGLEVEL"
      line: "LOGLEVEL=off"

  - name: Disable IPv6
    lineinfile:
      dest: /etc/default/ufw
      regexp: "^IPV6"
      line: "IPV6=no"

  - name: Change the default forward policy
    lineinfile:
      dest: /etc/default/ufw
      regexp: "^DEFAULT_FORWARD_POLICY"
      line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

  - name: Ensure UFW is enabled and denies by default
    ufw:
      state: "enabled"
      policy: "deny"
      direction: "incoming"

  - name: Ensure UFW allows Shadowsocks
    ufw:
      to_port: "1080"
      proto: "any"
      rule: "allow"
