version: '3.1'
services:
  sox:
    build: .
    container_name: sox
    depends_on:
      - sho
    environment:
      CIPHER_TYPE: chacha20-ietf-poly1305
      MODE: server
      REMOTE_ADDR: 0.0.0.0
      REMOTE_PORT: 8888
      REMOTE_PSS_FILE: /run/secrets/sox_secret
    image: 9bkerzya/shosox:sox
    network_mode: service:sho
    privileged: true
    secrets:
      - sox_secret

  sho:
    container_name: sho
    dns:
      - 1.1.1.1
    environment:
      LAN_NETWORK: "192.168.193.0/24"
    image: 9bkerzya/shosox:sho
    networks:
      - sho_vpn
    ports:
      - "8888:8888"
      - "8888:8888/udp"
    privileged: true
    volumes:
      - /home/samba/backup/ovpn-files:/ovpn-files

secrets:
  sox_secret:
    file: sox_pss.txt

networks:
  sho_vpn:
